- name: Distribute keys to nodes
  hosts: servers

  tasks:
  - name: Copy key from server to nodes 
    ansible.builtin.copy:
      src: /home/srv/keys/key.txt
      dest: /home/node/check.txt
      