- name: Retrieve keys from nodes
  hosts: servers

  tasks:
  - name: Fetch checks from nodes to server
    ansible.builtin.fetch:
      src: /home/node/check.txt
      dest: /home/srv/keys/check_{{ ansible_hostname }}.txt