- name: Retrieve keys from nodes
  hosts: sshservers
  remote_user: root

  tasks:
  - name: Fetch checks from nodes to server
    ansible.builtin.fetch:
      src: /home/node/check.txt
      dest: /home/srv/keys/check_{{ ansible_hostname }}.txt